# Generated by Django 6.0.6 on 2026-06-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_name", models.CharField(max_length=100)),
                ("asset_type", models.CharField(max_length=100)),
                ("serial_number", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
    ]
