# Generated by Django 6.0.5 on 2026-06-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_vendor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Software",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("software_name", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=50)),
                ("license_key", models.CharField(max_length=100)),
                ("expiry_date", models.DateField()),
                ("status", models.CharField(max_length=50)),
            ],
        ),
    ]
