# Generated by Django 6.0.5 on 2026-06-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_software"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=200)),
                ("employee", models.CharField(max_length=100)),
                ("priority", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
            ],
        ),
    ]
