# Generated by Django 6.0.6 on 2026-06-08 06:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="assigned_engineer",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="ticket",
            name="category",
            field=models.CharField(
                choices=[("Hardware", "Hardware"), ("Software", "Software")],
                default="",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="assets.employee"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("Assigned", "Assigned"),
                    ("In Progress", "In Progress"),
                    ("Resolved", "Resolved"),
                    ("Closed", "Closed"),
                ],
                default="Open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_id",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
