# Generated by Django 6.0.5 on 2026-06-10 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0006_ticket_assigned_engineer_ticket_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.employee",
            ),
        ),
    ]
