# Generated by Django 6.0.5 on 2026-06-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_asset_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="asset_tag",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="error_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="impact_level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_id",
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
