# Generated by Django 6.0.5 on 2026-06-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0008_ticket_asset_tag_ticket_error_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="hardware_attachments/"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="hardware_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Desktop", "Desktop"),
                    ("Laptop", "Laptop"),
                    ("Printer/Scanner", "Printer/Scanner"),
                    ("IP Phone", "IP Phone"),
                    ("Network/Wi-Fi", "Network/Wi-Fi"),
                    ("Peripherals", "Peripherals"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="screenshot",
            field=models.ImageField(
                blank=True, null=True, upload_to="software_screenshots/"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="software_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Windows OS", "Windows OS"),
                    ("Antivirus", "Antivirus"),
                    ("PDF Reader", "PDF Reader"),
                    ("Browser Issues", "Browser Issues"),
                    ("Local Driver Software", "Local Driver Software"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
