# Generated by Django 6.0.5 on 2026-06-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0009_ticket_attachment_ticket_hardware_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="screenshot",
            field=models.FileField(
                blank=True, null=True, upload_to="software_screenshots/"
            ),
        ),
    ]
