# Generated by Django 6.0.5 on 2026-06-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0010_alter_ticket_screenshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcelUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("excel_file", models.FileField(upload_to="excel_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
